export const activities = [
    "Creates content", "Conducts reviews", "Shares insights", "Offers consultations", "Hosts webinars",
    "Leads discussions", "Participates in panels", "Collaborates with projects", "Educates followers", "Engages with community",
    "Organizes events", "Produces podcasts", "Writes articles", "Shares news", "Provides analysis",
    "Shares market updates", "Publishes research", "Develops tutorials", "Hosts AMAs (Ask Me Anything)", "Runs workshops",
    "Facilitates meetups", "Moderates forums", "Contributes to open-source projects", "Mentors newcomers", "Provides coaching",
    "Promotes blockchain adoption", "Advocates for decentralization", "Facilitates networking", "Engages in advocacy", "Partnerships",
    "Promotes financial literacy", "Promotes blockchain education", "Supports charity initiatives", "Promotes diversity and inclusion", "Promotes sustainability",
    "Participates in hackathons", "Supports regulatory compliance", "Promotes security practices", "Encourages innovation", "Supports entrepreneurship",
    "Promotes privacy protection", "Supports social impact projects", "Facilitates industry collaborations", "Promotes technological innovation", "Supports ecosystem growth",
    "Encourages responsible investing", "Encourages community involvement", "Promotes digital sovereignty", "Supports data integrity", "Advocates for financial inclusion",
    "Promotes transparent governance", "Supports cross-border transactions", "Encourages user empowerment", "Supports interoperability", "Advocates for fair access",
    "Promotes consensus mechanisms", "Supports scalability solutions", "Encourages adoption of smart contracts", "Advocates for digital identities", "Supports tokenization",
    "Promotes decentralization of finance", "Encourages peer-to-peer transactions", "Supports decentralization of governance", "Advocates for self-sovereign identity", "Supports distributed storage solutions",
    "Promotes blockchain interoperability", "Encourages adoption of cryptographic techniques", "Supports blockchain-based voting systems", "Advocates for blockchain-based supply chain management", "Supports decentralized data management solutions",
    "Promotes blockchain-based energy solutions", "Encourages adoption of blockchain for healthcare", "Supports blockchain-based educational initiatives", "Advocates for blockchain-based digital identities", "Supports blockchain-based intellectual property rights",
    "Promotes blockchain-based content monetization", "Encourages adoption of blockchain for renewable energy", "Supports blockchain-based real estate solutions", "Advocates for blockchain-based asset tracking", "Supports blockchain-based legal solutions",
    "Promotes blockchain-based authentication systems", "Encourages adoption of blockchain for environmental conservation", "Supports blockchain-based provenance tracking", "Advocates for blockchain-based voting systems", "Supports blockchain-based humanitarian aid",
    "Promotes blockchain-based social impact projects", "Encourages adoption of blockchain for supply chain transparency", "Supports blockchain-based identity verification", "Advocates for blockchain-based content ownership", "Supports blockchain-based digital rights management",
];
