export const expertise = [
    "Expert", "Specialist", "Professional", "Enthusiast", "Guru",
    "Advocate", "Evangelist", "Aficionado", "Proponent", "Analyst",
    "Strategist", "Leader", "Influencer", "Pioneer", "Visionary",
    "Innovator", "Trailblazer", "Mentor", "Coach", "Educator",
    "Speaker", "Author", "Consultant", "Ambassador", "Creator",
    "Futurist", "Thought Leader", "SME (Subject Matter Expert)", "Guide", "Authority",
    "Trainer", "Trendsetter", "Champion", "Changemaker", "Contributor",
    "Driver", "Facilitator", "Keynote Speaker", "Lecturer", "Moderator",
    "Presenter", "Promoter", "Advancer", "Exemplar", "Inspiration",
    "Motivator", "Navigator", "Pathfinder", "Steward", "Supporter",
    "Advocator", "Campaigner", "Enabler", "Exponent", "Instigator",
    "Pathbreaker", "Patron", "Propagator", "Standard Bearer", "Trailblazer",
    "Vanguard", "Catalyst", "Leader", "Teacher", "Expertise", 
    "Resource", "Contributor", "Professionalism", "Competency",
    "Authority", "Instructor", "Master", "Skill", "Talent",
    "Proficiency", "Adeptness", "Specialty", "Capability", "Craftsmanship",
    "Knowledge", "Understanding", "Wisdom", "Experience", "Mastery",
    "Adept", "Maestro", "Savvy", "Whiz", "Veteran",
    "Connoisseur", "Connoisseurship", "Familiarity", "Expertness", "Fluency",
    "Prowess", "Expertise", "Command", "Concinnity", "Artistry",
    "Finesse", "Know-how", "Proficient", "Savant", "Skillfulness",
];
