export const interests = [
    "Blockchain", "Cryptocurrencies", "DeFi", "NFTs", "Investing",
    "Trading", "Smart Contracts", "Digital Assets", "Cryptocurrency Mining", "Blockchain Technology",
    "Ethereum", "Bitcoin", "Altcoins", "Decentralized Applications", "Tokenization",
    "Security Tokens", "Stablecoins", "Crypto Exchanges", "Decentralized Finance", "Web3",
    "Blockchain Gaming", "DAOs (Decentralized Autonomous Organizations)", "Cryptocurrency Wallets", "DApps",
    "Crypto Regulations", "Crypto Adoption", "Cryptocurrency Trading Strategies", "Decentralization", "Blockchain Scalability",
    "Crypto News", "Blockchain Interoperability", "Cryptocurrency Investment Funds", "Crypto Payments", "Crypto Lending",
    "Blockchain Education", "Privacy Coins", "Cryptocurrency Taxes", "Blockchain Development", "Cryptocurrency Futures",
    "Blockchain Governance", "Decentralized Identity", "Cross-Chain Solutions", "Cryptocurrency Market Analysis", "Layer 2 Solutions",
    "Crypto Hardware Wallets", "Blockchain Use Cases", "Smart Contract Auditing", "Crypto Derivatives", "Blockchain Research",
    "Cryptocurrency Investment Strategies", "Tokenomics", "Blockchain Security", "Crypto Trading Bots", "Decentralized Exchanges",
    "Crypto Market Trends", "Blockchain Consulting", "Digital Identity", "Crypto Asset Management", "Blockchain Privacy",
    "Crypto Crowdfunding", "Token Standards", "Blockchain Integration", "Crypto Regulation Compliance", "Blockchain Patents",
    "Cryptocurrency Mining Pools", "Blockchain Oracles", "Crypto Asset Valuation", "Blockchain Supply Chain", "Crypto Asset Tokenization",
    "Blockchain Voting Systems", "Non-Custodial Wallets", "Crypto Asset Insurance", "Blockchain Crowdfunding", "Blockchain Scaling Solutions",
    "Crypto Trading Signals", "Decentralized Autonomous Corporations", "Crypto Hedge Funds", "Blockchain Real Estate", "Cryptocurrency Index Funds",
    "Blockchain Energy Solutions", "Crypto Market Volatility", "Decentralized Social Media", "Crypto Asset Tracking", "Blockchain Intellectual Property",
    "Cryptocurrency Futures Trading", "Crypto Margin Trading", "Blockchain Governance Models", "Decentralized Prediction Markets", "Crypto Asset Recovery",
    "Blockchain Healthcare Solutions", "Cryptocurrency Trading Platforms", "Blockchain Tokenization Platforms", "Crypto Asset Exchange Platforms", "Decentralized Asset Management",
    "Blockchain Identity Management", "Cryptocurrency Payment Gateways", "Blockchain Supply Chain Management", "Crypto Asset Custody Solutions", "Decentralized Insurance",
];
